kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-cluster
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin-1
  apiGroup: rbac.authorization.k8s.io